{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c76b0a4-e51b-43df-b8a4-6812010e11a3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def eeg_classifier_cv(time, data,train_index, test_index):\n",
    "    \n",
    "    # Define X, y\n",
    "    X = data.drop(columns=['Group']).values\n",
    "    y = data['Group'].values\n",
    "    \n",
    "    # Run classifier model by using cross-validation, feature-selection and storing results.\n",
    "    results = []\n",
    "\n",
    "    for clf_name, clf in classifiers.items():\n",
    "        print('Running:', clf_name)\n",
    "        for selector_nm, selector in feature_selector.items():\n",
    "            accuracy_scores = []\n",
    "            f1_scores = []\n",
    "            auc_scores = []\n",
    "\n",
    "            vote_accuracy_scores = []\n",
    "            vote_f1_scores = []\n",
    "            vote_auc_scores = []\n",
    "\n",
    "            sen_scores = []\n",
    "            spe_scores = []\n",
    "            ppv_scores = []\n",
    "            npv_scores = []                \n",
    "\n",
    "            vote_sen_scores = []\n",
    "            vote_spe_scores = []\n",
    "            vote_ppv_scores = []\n",
    "            vote_npv_scores = []                \n",
    "\n",
    "            vote_pred_list = []\n",
    "            vote_test_list = []\n",
    "            pred_list = []\n",
    "            test_list = []\n",
    "\n",
    "            X_train_num, X_test_num = train_index, test_index\n",
    "\n",
    "            X_train = []\n",
    "            y_train = []\n",
    "            vote_num = []\n",
    "            for X_tr in X_train_num:\n",
    "                if X_tr < 36:\n",
    "                    tr = np.load(\"D:/test5/raw\"+ str(X_tr+1) +\"_AD_\"+time+\".npy\")\n",
    "                    y_train += [1] * tr.shape[0]\n",
    "                elif X_tr > 35 and X_tr < 66:\n",
    "                    tr = np.load(\"D:/test5/raw\"+ str(X_tr) +\"_CN_\"+time+\".npy\") \n",
    "                    y_train += [0] * tr.shape[0]\n",
    "                elif X_tr > 65:\n",
    "                    tr = np.load(\"D:/test5/raw\"+ str(X_tr) +\"_FTD_\"+time+\".npy\")\n",
    "                    y_train += [1] * tr.shape[0]\n",
    "                else:\n",
    "                    print('none',X_tr)\n",
    "                X_train.append(tr)\n",
    "            X_train = np.concatenate(X_train, axis=0)\n",
    "\n",
    "            X_test = []\n",
    "            y_test = []\n",
    "            for X_te in X_test_num:\n",
    "                if X_te < 36:\n",
    "                    te = np.load(\"D:/test5/raw\" + str(X_te+1) + \"_AD_\" +time+ \".npy\")\n",
    "                    y_test += [1] * te.shape[0]\n",
    "                    vote_num.append(te.shape[0])\n",
    "                elif X_te > 35 and X_te < 66:\n",
    "                    te = np.load(\"D:/test5/raw\"+ str(X_te) +\"_CN_\"+time+\".npy\") \n",
    "                    y_test += [0] * te.shape[0]\n",
    "                    vote_num.append(te.shape[0])\n",
    "                elif X_te > 65:\n",
    "                    te = np.load(\"D:/test5/raw\"+ str(X_te) +\"_FTD_\"+time+\".npy\")\n",
    "                    \n",
    "                    y_test += [1] * te.shape[0]\n",
    "                    vote_num.append(te.shape[0])\n",
    "                X_test.append(te)                        \n",
    "            X_test = np.concatenate(X_test, axis=0)                   \n",
    "\n",
    "            scaler = StandardScaler()\n",
    "            X_train = scaler.fit_transform(X_train)\n",
    "            X_test = scaler.transform(X_test)\n",
    "\n",
    "            #X_train_selected = selector.fit_transform(X_train, y_train)\n",
    "            #X_test_selected = selector.transform(X_test)\n",
    "            X_train_selected = X_train\n",
    "            X_test_selected = X_test\n",
    "\n",
    "            # Train the classifier on the training data\n",
    "            clf.fit(X_train_selected, y_train)\n",
    "\n",
    "            # Make predictions on the test data\n",
    "            y_pred = clf.predict(X_test_selected)\n",
    "\n",
    "            # Calculate metrics for the current fold and append to the scores list\n",
    "            accuracy_scores.append(accuracy_score(y_true=y_test, y_pred=y_pred))\n",
    "            f1_scores.append(f1_score(y_true=y_test, y_pred=y_pred, average=\"macro\"))\n",
    "            auc_scores.append(roc_auc_score(y_test, y_pred, multi_class=\"ovr\"))\n",
    "            \n",
    "            tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()\n",
    "            sen = tp / (tp + fn) if (tp + fn) != 0 else 0\n",
    "            spe = tn / (fp + tn) if (fp + tn) != 0 else 0\n",
    "            ppv = tp / (tp + fp) if (tp + fp) != 0 else 0\n",
    "            npv = tn / (tn + fn) if (tn + fn) != 0 else 0\n",
    "\n",
    "            sen_scores.append(sen)\n",
    "            spe_scores.append(spe)\n",
    "            ppv_scores.append(ppv)\n",
    "            npv_scores.append(npv)\n",
    "\n",
    "            count_num = 0\n",
    "            vote_pred = []\n",
    "            vote_test = []\n",
    "            for v in vote_num:\n",
    "                count = Counter(y_pred[count_num:count_num+v])\n",
    "                most_common_value = count.most_common(1)[0][0]\n",
    "                vote_pred.append(most_common_value)\n",
    "\n",
    "                count = Counter(y_test[count_num:count_num+v])\n",
    "                most_common_value = count.most_common(1)[0][0]\n",
    "                vote_test.append(most_common_value)\n",
    "\n",
    "                count_num = count_num + v\n",
    "\n",
    "            vote_accuracy_scores.append(accuracy_score(y_true=vote_test, y_pred=vote_pred))\n",
    "            vote_f1_scores.append(f1_score(y_true=vote_test, y_pred=vote_pred, average=\"macro\"))\n",
    "            vote_auc_scores.append(roc_auc_score(vote_test, vote_pred, multi_class=\"ovr\"))\n",
    "\n",
    "            vote_tn, vote_fp, vote_fn, vote_tp = confusion_matrix(vote_test, vote_pred).ravel()\n",
    "            vote_sen = vote_tp / (vote_tp + vote_fn) if (vote_tp + vote_fn) != 0 else 0\n",
    "            vote_spe = vote_tn / (vote_fp + vote_tn) if (vote_fp + vote_tn) != 0 else 0\n",
    "            vote_ppv = vote_tp / (vote_tp + vote_fp) if (vote_tp + vote_fp) != 0 else 0\n",
    "            vote_npv = vote_tn / (vote_tn + vote_fn) if (vote_tn + vote_fn) != 0 else 0\n",
    "\n",
    "            vote_sen_scores.append(vote_sen)\n",
    "            vote_spe_scores.append(vote_spe)\n",
    "            vote_ppv_scores.append(vote_ppv)\n",
    "            vote_npv_scores.append(vote_npv)\n",
    "\n",
    "            vote_pred_list.append(vote_pred)\n",
    "            vote_test_list.append(vote_test)\n",
    "            pred_list.append(y_pred)\n",
    "            test_list.append(y_test)\n",
    "\n",
    "            # Save results for each option\n",
    "            result = {\n",
    "                'time': time,\n",
    "                'classifier': clf_name,\n",
    "                'feature-selection': selector_nm,\n",
    "                'accuracy': np.mean(accuracy_scores),\n",
    "                'f1_score': np.mean(f1_scores),\n",
    "                'AUC': np.mean(auc_scores),\n",
    "                'sen_scores': np.mean(sen_scores),\n",
    "                'spe_scores': np.mean(spe_scores),\n",
    "                'ppv_scores': np.mean(ppv_scores),\n",
    "                'npv_scores': np.mean(npv_scores),\n",
    "                'vote_accuracy': np.mean(vote_accuracy_scores),\n",
    "                'vote_f1_score': np.mean(vote_f1_scores),\n",
    "                'vote_AUC': np.mean(vote_auc_scores),\n",
    "                'vote_sen_scores': np.mean(vote_sen_scores),\n",
    "                'vote_spe_scores': np.mean(vote_spe_scores),\n",
    "                'vote_ppv_scores': np.mean(vote_ppv_scores),\n",
    "                'vote_npv_scores': np.mean(vote_npv_scores),\n",
    "                'std_accuracy': np.std(accuracy_scores),\n",
    "                'std_f1_score': np.std(f1_scores),\n",
    "                'std_AUC': np.std(auc_scores),\n",
    "                'std_sen_scores': np.std(sen_scores),\n",
    "                'std_spe_scores': np.std(spe_scores),\n",
    "                'std_ppv_scores': np.std(ppv_scores),\n",
    "                'std_npv_scores': np.std(npv_scores),\n",
    "                'std_vote_accuracy': np.std(vote_accuracy_scores),\n",
    "                'std_vote_f1_score': np.std(vote_f1_scores),\n",
    "                'std_vote_AUC': np.std(vote_auc_scores),\n",
    "                'std_vote_sen_scores': np.std(vote_sen_scores),\n",
    "                'std_vote_spe_scores': np.std(vote_spe_scores),\n",
    "                'std_vote_ppv_scores': np.std(vote_ppv_scores),\n",
    "                'std_vote_npv_scores': np.std(vote_npv_scores),\n",
    "                'test': test_list, \n",
    "                'pred': pred_list,\n",
    "                'vote_test': vote_test_list, \n",
    "                'vote_pred': vote_pred_list,\n",
    "                #'selected_features': selector.get_support(indices=True)  # 선택된 특징 인덱스 추가\n",
    "            }\n",
    "\n",
    "            results.append(result)\n",
    "    df_results = pd.DataFrame(results)\n",
    "    return df_results#, clf\n",
    "#여기\n",
    "#분류\n",
    "total_total_df_AD_CN = pd.DataFrame()\n",
    "total_total_df_FTD_CN = pd.DataFrame()\n",
    "total_total_df_AD_FTD_CN = pd.DataFrame()\n",
    "total_total_df_AD_FTD = pd.DataFrame()\n",
    "\n",
    "\n",
    "\n",
    "for r in random_list:\n",
    "#여기\n",
    "\n",
    "    total_df_AD_CN = pd.DataFrame()\n",
    "    total_df_FTD_CN = pd.DataFrame()\n",
    "    total_df_AD_FTD = pd.DataFrame()\n",
    "    total_df_AD_FTD_CN = pd.DataFrame()\n",
    "\n",
    "    results = []\n",
    "    random.seed(r)\n",
    "    for k in data_segments.keys():\n",
    "        print('time: ',k)\n",
    "\n",
    "\n",
    "        AD_total=0\n",
    "        for i in range(len(a)):\n",
    "            n = np.load(\"D:/test5/raw\"+str(i+1)+\"_AD_\"+k+\".npy\").shape[0]\n",
    "            AD_total+= n\n",
    "        su=0\n",
    "        AD_te = []\n",
    "        numbers = list(range(0, len(a)))\n",
    "        selected_indices = set()\n",
    "        while su < AD_total*0.1:\n",
    "            r = random.randint(0,len(a)-1)\n",
    "            if r not in selected_indices:\n",
    "                n = np.load(\"D:/test5/raw\" + str(r+1) + \"_AD_\" + k + \".npy\")\n",
    "                su += n.shape[0]\n",
    "                AD_te.append(r)\n",
    "                selected_indices.add(r)\n",
    "        AD_te.pop()\n",
    "        AD_tr = [num for num in numbers if num not in AD_te]\n",
    "\n",
    "        FTD_total=0\n",
    "        for i in range(len(t)):\n",
    "            n = np.load(\"D:/test5/raw\"+str(i+66)+\"_FTD_\"+k+\".npy\").shape[0]\n",
    "            FTD_total+= n    \n",
    "        su=0\n",
    "        FTD_te = []\n",
    "        numbers = list(range(len(a)+len(c)+1, len(a)+len(c)+len(t)+1))\n",
    "        selected_indices = set()\n",
    "        while su < FTD_total*0.1:\n",
    "            r = random.randint(len(a)+len(c)+1,len(a)+len(c)+len(t))\n",
    "            if r not in selected_indices:\n",
    "                n = np.load(\"D:/test5/raw\" + str(r) + \"_FTD_\" + k + \".npy\")\n",
    "                su += n.shape[0]\n",
    "                FTD_te.append(r)\n",
    "                selected_indices.add(r)\n",
    "\n",
    "        FTD_te.pop()\n",
    "        FTD_tr = [num for num in numbers if num not in FTD_te]\n",
    "\n",
    "        CN_total=0\n",
    "        for i in range(len(c)):\n",
    "            n = np.load(\"D:/test5/raw\"+str(i+37)+\"_CN_\"+k+\".npy\").shape[0]\n",
    "            CN_total+= n   \n",
    "        su=0\n",
    "        CN_te = []\n",
    "        numbers = list(range(len(a)+1, len(a)+len(c)+1))\n",
    "        selected_indices = set()\n",
    "        while su < CN_total*0.1:\n",
    "            r = random.randint(len(a)+1,len(a)+len(c))\n",
    "            if r not in selected_indices:\n",
    "                n = np.load(\"D:/test5/raw\" + str(r) + \"_CN_\" + k + \".npy\")\n",
    "                su += n.shape[0]\n",
    "                CN_te.append(r)\n",
    "                selected_indices.add(r)    \n",
    "        CN_te.pop()\n",
    "        CN_tr = [num for num in numbers if num not in CN_te]\n",
    "\n",
    "\n",
    "        #AD_FTD = np.concatenate((AD_feature, FTD_feature))\n",
    "        #AD_CN = np.concatenate((np.load(\"C:/total/total/AD_total_+\"+k+\".npy\"), np.load(\"C:/total/total/CN_total_+\"+k+\".npy\")))\n",
    "        #FTD_CN = np.concatenate((np.load(\"C:/total/total/FTD_total_+\"+k+\".npy\"), np.load(\"C:/total/total/CN_total_+\"+k+\".npy\")))\n",
    "        #np.save(\"C:/total/feature/AD_CN_\"+k, AD_CN)\n",
    "        #np.save(\"C:/total/feature/FTD_CN_\"+k, FTD_CN)\n",
    "\n",
    "\n",
    "\n",
    "        AD_CN_tr = AD_tr+CN_tr\n",
    "        AD_CN_te = AD_te+CN_te\n",
    "\n",
    "        FTD_CN_tr = FTD_tr+CN_tr\n",
    "        FTD_CN_te = FTD_te+CN_te\n",
    "\n",
    "        AD_FTD_CN_tr = AD_tr+FTD_tr+CN_tr\n",
    "        AD_FTD_CN_te = AD_te+FTD_te+CN_te\n",
    "        \n",
    "     \n",
    "        \n",
    "\n",
    "\n",
    "        #random.shuffle(AD_CN_tr)\n",
    "        #random.shuffle(AD_CN_te)\n",
    "\n",
    "        #random.shuffle(FTD_CN_tr)\n",
    "        #random.shuffle(FTD_CN_te)\n",
    "\n",
    "        #random.shuffle(AD_FTD_CN_tr)\n",
    "        #random.shuffle(AD_FTD_CN_te)\n",
    "\n",
    "   \n",
    "\n",
    "\n",
    "        df_results_cv_allch_AD_CN = eeg_classifier_cv(k, ad_cn, AD_CN_tr, AD_CN_te)\n",
    "\n",
    "        total_df_AD_CN = pd.concat((total_df_AD_CN,df_results_cv_allch_AD_CN))\n",
    "\n",
    "\n",
    "\n",
    "        df_results_cv_allch_FTD_CN = eeg_classifier_cv(k, ftd_cn, FTD_CN_tr, FTD_CN_te)\n",
    "\n",
    "\n",
    "        total_df_FTD_CN = pd.concat((total_df_FTD_CN,df_results_cv_allch_FTD_CN))\n",
    "\n",
    "\n",
    "\n",
    "        df_results_cv_allch_AD_FTD_CN = eeg_classifier_cv(k, ad_ftd_cn, AD_FTD_CN_tr, AD_FTD_CN_te)\n",
    "\n",
    "        total_df_AD_FTD_CN = pd.concat((total_df_AD_FTD_CN,df_results_cv_allch_AD_FTD_CN))\n",
    "\n",
    "\n",
    "        \n",
    "        \n",
    "\n",
    "    total_total_df_AD_CN = pd.concat((total_total_df_AD_CN,total_df_AD_CN))\n",
    "\n",
    "    total_total_df_FTD_CN = pd.concat((total_total_df_FTD_CN,total_df_FTD_CN))\n",
    "\n",
    "    total_total_df_AD_FTD_CN = pd.concat((total_total_df_AD_FTD_CN,total_df_AD_FTD_CN))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
