{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1bd11de9-4df6-435a-a6d1-98a0adeea11b",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "num = 1\n",
    "\n",
    "   \n",
    "for i,j in enumerate(a):\n",
    "    variable_name = f'raw{num}'\n",
    "    path = \"D:/data/derivatives/\"+ j + \"/eeg/\"+ j + \"_task-eyesclosed_eeg.set\"\n",
    "    eeg_data = mne.io.read_raw_eeglab(path, preload=True)\n",
    "    eeg_data.filter(0.5, 45, fir_design = \"firwin\", skip_by_annotation=\"edge\", verbose=0)\n",
    "    #eeg_data = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #globals()[variable_name] = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #eeg_data = globals()[variable_name].get_data()\n",
    "#    data_segments = {}\n",
    "#    for w in window_lengths:\n",
    "#        for m in moving_lengths:\n",
    "#            key = f'w{w}_m{m}'\n",
    "#            if key not in data_segments:\n",
    "#                data_segments[key] = []\n",
    "            # EEG 데이터를 시간 간격에 따라 자르기\n",
    "#            split_data = split_eeg_data(eeg_data.get_data(), w, m)\n",
    "            # NaN 값을 포함하지 않는 데이터 세그먼트 추가\n",
    "            #valid_data_segments = [data for data in split_data if not np.isnan(data).any()]\n",
    "#            data_segments[key].extend(split_data)\n",
    "    #del globals()[variable_name]            \n",
    "    #num += 1\n",
    "\n",
    "    \n",
    "    data_segments = {}\n",
    "    for w in window_lengths:\n",
    "        for m in moving_lengths:\n",
    "            key = f'w{w}_m{m}'\n",
    "            if key not in data_segments:\n",
    "                data_segments[key] = []\n",
    "            # Segment the data\n",
    "            tmin = 0\n",
    "            while tmin + w - 1/500 < eeg_data.times.max():\n",
    "                tmax = tmin + w - 1/500\n",
    "                data = eeg_data.copy()\n",
    "                data_segments[key].append(data.crop(tmin, tmax).get_data())\n",
    "                tmin += m\n",
    "#     del globals()[variable_name]            \n",
    "#     #num += 1\n",
    "    \n",
    "\n",
    "    for k in data_segments.keys():\n",
    "        eeg_data = data_segments[k]\n",
    "        eeg_data = np.array(eeg_data)\n",
    "        activity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        mobility = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        complexity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "\n",
    "        for i in range(eeg_data.shape[0]):\n",
    "            for j in range(eeg_data.shape[1]):\n",
    "                channel = eeg_data[i, j, :]\n",
    "\n",
    "                activity[i,j] = channel.var()\n",
    "                mobility[i, j] = hjorth_mobility(channel)\n",
    "                complexity[i, j] = hjorth_complexity(channel)\n",
    "\n",
    "        activity_n = np.array(activity)\n",
    "        mobility_n = np.array(mobility)\n",
    "        complexity_n = np.array(complexity)\n",
    "        np.save(\"D:/test3/raw\"+str(num)+\"_AD_\"+k, np.column_stack((activity_n, mobility_n, complexity_n)))\n",
    "    num += 1\n",
    "\n",
    "\n",
    "for i,j in enumerate(c):\n",
    "    variable_name = f'raw{num}'\n",
    "    path = \"D:/data/derivatives/\"+ j + \"/eeg/\"+ j + \"_task-eyesclosed_eeg.set\"\n",
    "    eeg_data = mne.io.read_raw_eeglab(path, preload=True)\n",
    "    eeg_data.filter(0.5, 45, fir_design = \"firwin\", skip_by_annotation=\"edge\", verbose=0)\n",
    "    #eeg_data = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #globals()[variable_name] = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #eeg_data = globals()[variable_name].get_data()\n",
    "#    data_segments = {}\n",
    "#    for w in window_lengths:\n",
    "#        for m in moving_lengths:\n",
    "#            key = f'w{w}_m{m}'\n",
    "#            if key not in data_segments:\n",
    "#                data_segments[key] = []\n",
    "            # EEG 데이터를 시간 간격에 따라 자르기\n",
    "#            split_data = split_eeg_data(eeg_data.get_data(), w, m)\n",
    "            # NaN 값을 포함하지 않는 데이터 세그먼트 추가\n",
    "            #valid_data_segments = [data for data in split_data if not np.isnan(data).any()]\n",
    "#            data_segments[key].extend(split_data)\n",
    "    #del globals()[variable_name]            \n",
    "    #num += 1\n",
    "    \n",
    "    \n",
    "    data_segments = {}\n",
    "    for w in window_lengths:\n",
    "        for m in moving_lengths:\n",
    "            key = f'w{w}_m{m}'\n",
    "            if key not in data_segments:\n",
    "                data_segments[key] = []\n",
    "\n",
    "             # Segment the data\n",
    "            tmin = 0\n",
    "            while tmin + w - 1/500 < eeg_data.times.max():\n",
    "                tmax = tmin + w - 1/500\n",
    "                data = eeg_data.copy()\n",
    "                data_segments[key].append(data.crop(tmin, tmax).get_data())\n",
    "                tmin += m\n",
    "#     del globals()[variable_name]            \n",
    "#     #num += 1\n",
    "\n",
    "    for k in data_segments.keys():\n",
    "        eeg_data = data_segments[k]\n",
    "        eeg_data = np.array(eeg_data)\n",
    "        activity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        mobility = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        complexity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "\n",
    "        for i in range(eeg_data.shape[0]):\n",
    "            for j in range(eeg_data.shape[1]):\n",
    "                channel = eeg_data[i, j, :]\n",
    "\n",
    "                activity[i,j] = channel.var()\n",
    "                mobility[i, j] = hjorth_mobility(channel)\n",
    "                complexity[i, j] = hjorth_complexity(channel)\n",
    "\n",
    "        activity_n = np.array(activity)\n",
    "        mobility_n = np.array(mobility)\n",
    "        complexity_n = np.array(complexity)\n",
    "        np.save(\"D:/test3/raw\"+str(num)+\"_CN_\"+k, np.column_stack((activity_n, mobility_n, complexity_n)))\n",
    "    num += 1\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "for i,j in enumerate(t):\n",
    "    variable_name = f'raw{num}'\n",
    "    path = \"D:/data/derivatives/\"+ j + \"/eeg/\"+ j + \"_task-eyesclosed_eeg.set\"\n",
    "    eeg_data = mne.io.read_raw_eeglab(path, preload=True)\n",
    "    eeg_data.filter(0.5, 45, fir_design = \"firwin\", skip_by_annotation=\"edge\", verbose=0)\n",
    "    #eeg_data = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #globals()[variable_name] = bandpass_filter(globals()[variable_name], 0.5, 45, fs = 500, order=5)    \n",
    "    #eeg_data = globals()[variable_name].get_data()\n",
    "#    data_segments = {}\n",
    "#    for w in window_lengths:\n",
    "#        for m in moving_lengths:\n",
    "#            key = f'w{w}_m{m}'\n",
    "#            if key not in data_segments:\n",
    "#                data_segments[key] = []\n",
    "            # EEG 데이터를 시간 간격에 따라 자르기\n",
    "#            split_data = split_eeg_data(eeg_data.get_data(), w, m)\n",
    "            # NaN 값을 포함하지 않는 데이터 세그먼트 추가\n",
    "            #valid_data_segments = [data for data in split_data if not np.isnan(data).any()]\n",
    "#            data_segments[key].extend(split_data)\n",
    "    #del globals()[variable_name]            \n",
    "    #num += 1\n",
    "    \n",
    "    \n",
    "    \n",
    "    data_segments = {}\n",
    "    for w in window_lengths:\n",
    "        for m in moving_lengths:\n",
    "            key = f'w{w}_m{m}'\n",
    "            if key not in data_segments:\n",
    "                data_segments[key] = []\n",
    "\n",
    "#             # Segment the data\n",
    "            tmin = 0\n",
    "            while tmin + w - 1/500 < eeg_data.times.max():\n",
    "                tmax = tmin + w - 1/500\n",
    "                data =eeg_data.copy()\n",
    "                data_segments[key].append(data.crop(tmin, tmax).get_data())\n",
    "                tmin += m\n",
    "#     del globals()[variable_name]            \n",
    "#     #num += 1\n",
    "\n",
    "\n",
    "    for k in data_segments.keys():\n",
    "        eeg_data = data_segments[k]\n",
    "        eeg_data = np.array(eeg_data)\n",
    "        activity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        mobility = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "        complexity = np.zeros((eeg_data.shape[0], eeg_data.shape[1]))\n",
    "\n",
    "        for i in range(eeg_data.shape[0]):\n",
    "            for j in range(eeg_data.shape[1]):\n",
    "                channel = eeg_data[i, j, :]\n",
    "\n",
    "                activity[i,j] = channel.var()\n",
    "                mobility[i, j] = hjorth_mobility(channel)\n",
    "                complexity[i, j] = hjorth_complexity(channel)\n",
    "\n",
    "        activity_n = np.array(activity)\n",
    "        mobility_n = np.array(mobility)\n",
    "        complexity_n = np.array(complexity)\n",
    "        np.save(\"D:/test3/raw\"+str(num)+\"_FTD_\"+k, np.column_stack((activity_n, mobility_n, complexity_n)))\n",
    "    num += 1\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
